// src/components/sections/techstack.vue
<script setup>
import {
    MonitorCog,
    Code2,
    Wrench,
    Palette,
    Monitor,
    HardDrive,
    Bug,
    Printer,
    Network,
    Wifi,
    Camera,
    Headphones,
    Cpu,
    Globe,
    Braces,
    Database,
    FileCode2,
    Layout,
    Wind,
    Layers,
    Terminal,
    Server,
    FolderCog,
    Github,
    MonitorSmartphone,
    MousePointer2,
    FileSpreadsheet,
    Image,
    Figma,
    Video,
    Scissors,
    CheckCircle2,
} from 'lucide-vue-next'

const techStack = [
    {
        category: 'IT SUPPORT',
        description: 'Systems, troubleshooting & infrastructure',
        icon: MonitorCog,
        accent: 'teal',
        items: [
            {
                name: 'Windows 10/11',
                icon: Monitor,
            },
            {
                name: 'Hardware Troubleshooting',
                icon: HardDrive,
            },
            {
                name: 'Software Troubleshooting',
                icon: Bug,
            },
            {
                name: 'Printer Support',
                icon: Printer,
            },
            {
                name: 'Network Troubleshooting',
                icon: Network,
            },
            {
                name: 'LAN / Wi-Fi',
                icon: Wifi,
            },
            {
                name: 'CCTV',
                icon: Camera,
            },
            {
                name: 'Remote Support',
                icon: Headphones,
            },
            {
                name: 'PC Maintenance',
                icon: Cpu,
            },
        ],
    },

    {
        category: 'WEB DEVELOPMENT',
        description: 'Web applications & development',
        icon: Code2,
        accent: 'amber',
        items: [
            {
                name: 'HTML',
                icon: Globe,
            },
            {
                name: 'CSS',
                icon: FileCode2,
            },
            {
                name: 'JavaScript',
                icon: Braces,
            },
            {
                name: 'PHP',
                icon: Code2,
            },
            {
                name: 'MySQL',
                icon: Database,
            },
            {
                name: 'Vue.js',
                icon: Layers,
            },
            {
                name: 'Tailwind CSS',
                icon: Wind,
            },
            {
                name: 'Bootstrap',
                icon: Layout,
            },
        ],
    },

    {
        category: 'TOOLS & WORKFLOW',
        description: 'Development, IT support & productivity',
        icon: Wrench,
        accent: 'teal',
        items: [
            {
                name: 'VS Code',
                icon: Terminal,
            },
            {
                name: 'XAMPP',
                icon: Server,
            },
            {
                name: 'phpMyAdmin',
                icon: Database,
            },
            {
                name: 'GitHub',
                icon: Github,
            },
            {
                name: 'AnyDesk',
                icon: MonitorSmartphone,
            },
            {
                name: 'TeamViewer',
                icon: MonitorSmartphone,
            },
            {
                name: 'Microsoft Office',
                icon: FileSpreadsheet,
            },
        ],
    },

    {
        category: 'DESIGN & MEDIA',
        description: 'Basic design, UI/UX & media editing',
        icon: Palette,
        accent: 'amber',
        items: [
            {
                name: 'Photoshop',
                icon: Image,
            },
            {
                name: 'Canva',
                icon: Palette,
            },
            {
                name: 'Figma',
                icon: Figma,
            },
            {
                name: 'DaVinci Resolve',
                icon: Video,
            },
            {
                name: 'CapCut',
                icon: Scissors,
            },
        ],
    },
]
</script>

<template>
    <section id="techstack" class="
            relative
            flex
            min-h-screen
            items-center
            overflow-hidden
            bg-[#F7F7F5]
            px-5
            py-20
            text-zinc-900
            transition-colors
            duration-500

            dark:bg-[#0D1210]
            dark:text-white

            sm:px-8
            lg:px-10
            lg:py-24
            xl:px-14
        ">
        <!-- Background -->
        <div class="
                pointer-events-none
                absolute
                inset-0
                overflow-hidden
            " aria-hidden="true">
            <div class="
                    absolute
                    -right-32
                    top-1/4
                    h-96
                    w-96
                    rounded-full
                    bg-teal-200/20
                    blur-[100px]

                    dark:bg-teal-900/15
                "></div>

            <div class="
                    absolute
                    -bottom-32
                    left-1/4
                    h-72
                    w-72
                    rounded-full
                    bg-amber-200/15
                    blur-[100px]

                    dark:bg-amber-900/10
                "></div>

            <div class="
                    absolute
                    inset-0
                    opacity-[0.025]

                    dark:opacity-[0.035]
                " style="
                    background-image:
                        linear-gradient(
                            to right,
                            currentColor 1px,
                            transparent 1px
                        ),
                        linear-gradient(
                            to bottom,
                            currentColor 1px,
                            transparent 1px
                        );
                    background-size: 46px 46px;
                "></div>
        </div>

        <div class="
                relative
                z-10
                mx-auto
                w-full
                max-w-[1120px]
            ">
            <!-- Header -->
            <div class="
                    grid
                    gap-8

                    lg:grid-cols-[1fr_auto]
                    lg:items-end
                ">
                <div>
                    <div class="
                            mb-5
                            flex
                            items-center
                            gap-3
                            font-mono
                            text-[9px]
                            font-semibold
                            uppercase
                            tracking-[0.22em]
                            text-teal-700

                            dark:text-teal-400
                        ">
                        <span class="
                                relative
                                flex
                                h-1.5
                                w-1.5
                            ">
                            <span class="
                                    absolute
                                    inline-flex
                                    h-full
                                    w-full
                                    animate-ping
                                    rounded-full
                                    bg-teal-400
                                    opacity-60
                                "></span>

                            <span class="
                                    relative
                                    inline-flex
                                    h-1.5
                                    w-1.5
                                    rounded-full
                                    bg-teal-500
                                "></span>
                        </span>

                        Technical Toolkit
                    </div>

                    <h2 class="
                            max-w-3xl
                            text-[2.7rem]
                            font-black
                            leading-[0.9]
                            tracking-[-0.06em]

                            sm:text-4xl

                            md:text-5xl

                            lg:text-[4.2rem]
                        ">
                        <span class="
                                text-zinc-950

                                dark:text-white
                            ">
                            Tools I
                        </span>

                        <span class="
                                text-teal-700

                                dark:text-teal-400
                            ">
                            WORK
                        </span>

                        <span class="
                                block
                                text-zinc-800

                                dark:text-zinc-300
                            ">
                            WITH<span class="text-amber-500">.</span>
                        </span>
                    </h2>

                    <p class="
                            mt-5
                            max-w-2xl
                            text-xs
                            leading-6
                            text-zinc-500

                            dark:text-zinc-400

                            sm:text-sm
                            sm:leading-7
                        ">
                        A practical toolkit built around technical support,
                        troubleshooting, web development, system maintenance,
                        and creative work.
                    </p>
                </div>

                <div class="
                        hidden
                        font-mono
                        text-[8px]
                        uppercase
                        tracking-[0.22em]
                        text-zinc-300

                        dark:text-zinc-700

                        lg:block
                    ">
                    <span class="
                            text-teal-500
                        ">
                        04
                    </span>

                    <span class="mx-2">
                        /
                    </span>

                    TECH STACK
                </div>
            </div>

            <!-- Cards -->
            <div class="
                    mt-10
                    grid
                    gap-4

                    sm:grid-cols-2

                    lg:gap-5
                ">
                <article v-for="(stack, index) in techStack" :key="stack.category" class="
                        group
                        relative
                        overflow-hidden
                        rounded-2xl
                        border
                        border-zinc-200
                        bg-white/70
                        p-5
                        backdrop-blur-sm
                        transition-all
                        duration-300

                        hover:-translate-y-1
                        hover:border-teal-200
                        hover:shadow-xl
                        hover:shadow-teal-900/[0.05]

                        dark:border-zinc-800
                        dark:bg-zinc-900/50

                        dark:hover:border-teal-900
                        dark:hover:shadow-teal-950/20
                    ">
                    <div class="
                            absolute
                            inset-x-0
                            top-0
                            h-px
                            bg-gradient-to-r
                            from-transparent
                            via-teal-500
                            to-transparent
                            opacity-0
                            transition-opacity
                            duration-300

                            group-hover:opacity-100
                        "></div>

                    <div class="
                            flex
                            items-start
                            justify-between
                            gap-4
                        ">
                        <div class="
                                flex
                                min-w-0
                                items-start
                                gap-3
                            ">
                            <div class="
                                    flex
                                    h-10
                                    w-10
                                    shrink-0
                                    items-center
                                    justify-center
                                    rounded-xl
                                    border
                                    border-teal-100
                                    bg-teal-50
                                    text-teal-700
                                    transition-all
                                    duration-300

                                    group-hover:scale-105
                                    group-hover:border-teal-200
                                    group-hover:bg-teal-100

                                    dark:border-teal-900
                                    dark:bg-teal-950/50
                                    dark:text-teal-400

                                    dark:group-hover:border-teal-800
                                    dark:group-hover:bg-teal-950
                                ">
                                <component :is="stack.icon" class="h-4.5 w-4.5" />
                            </div>

                            <div class="min-w-0">
                                <h3 class="
                                        font-mono
                                        text-[10px]
                                        font-bold
                                        uppercase
                                        tracking-[0.12em]
                                        text-zinc-900

                                        dark:text-zinc-100

                                        sm:text-xs
                                    ">
                                    {{ stack.category }}
                                </h3>

                                <p class="
                                        mt-1
                                        max-w-xs
                                        text-[9px]
                                        leading-4
                                        text-zinc-400

                                        dark:text-zinc-500
                                    ">
                                    {{ stack.description }}
                                </p>
                            </div>
                        </div>

                        <span class="
                                shrink-0
                                font-mono
                                text-[9px]
                                font-semibold
                                text-teal-500

                                dark:text-teal-600
                            ">
                            {{ String(index + 1).padStart(2, '0') }}
                        </span>
                    </div>

                    <div class="
                            my-5
                            h-px
                            bg-zinc-100

                            dark:bg-zinc-800
                        "></div>

                    <div class="
                            grid
                            grid-cols-2
                            gap-1.5
                        ">
                        <div v-for="item in stack.items" :key="item.name" class="
                                group/item
                                flex
                                min-w-0
                                items-center
                                gap-2
                                rounded-lg
                                border
                                border-zinc-200
                                bg-[#F7F7F5]
                                px-2.5
                                py-2
                                transition-all
                                duration-200

                                hover:border-teal-200
                                hover:bg-teal-50

                                dark:border-zinc-800
                                dark:bg-zinc-950/70

                                dark:hover:border-teal-900
                                dark:hover:bg-teal-950/40
                            ">
                            <component :is="item.icon" class="
                                    h-3
                                    w-3
                                    shrink-0
                                    text-zinc-400
                                    transition-colors
                                    duration-200

                                    group-hover/item:text-teal-600

                                    dark:text-zinc-600
                                    dark:group-hover/item:text-teal-400
                                " />

                            <span class="
                                    min-w-0
                                    truncate
                                    font-mono
                                    text-[8px]
                                    leading-4
                                    text-zinc-600
                                    transition-colors
                                    duration-200

                                    group-hover/item:text-teal-700

                                    dark:text-zinc-400
                                    dark:group-hover/item:text-teal-400

                                    sm:text-[9px]
                                ">
                                {{ item.name }}
                            </span>
                        </div>
                    </div>

                    <div class="
                            mt-5
                            flex
                            items-center
                            justify-between
                        ">
                        <span class="
                                flex
                                items-center
                                gap-1.5
                                font-mono
                                text-[7px]
                                uppercase
                                tracking-[0.18em]
                                text-zinc-400

                                dark:text-zinc-600
                            ">
                            <CheckCircle2 class="
                                    h-2.5
                                    w-2.5
                                    text-teal-500
                                " />

                            {{ stack.items.length }} skills
                        </span>

                        <span class="
                                h-1.5
                                w-1.5
                                rounded-full
                                bg-teal-500
                                opacity-30
                                transition-all
                                duration-300

                                group-hover:scale-150
                                group-hover:opacity-100
                            "></span>
                    </div>
                </article>
            </div>

            <!-- Footer -->
            <div class="
                    mt-8
                    flex
                    flex-col
                    items-center
                    justify-between
                    gap-3
                    border-t
                    border-zinc-200
                    pt-6

                    dark:border-zinc-800

                    sm:flex-row
                ">
                <div class="
                        flex
                        items-center
                        gap-2
                        font-mono
                        text-[8px]
                        uppercase
                        tracking-[0.16em]
                        text-zinc-400

                        dark:text-zinc-600
                    ">
                    <span class="
                            h-1.5
                            w-1.5
                            rounded-full
                            bg-teal-500
                        "></span>

                    Continuously learning & expanding
                </div>

                <div class="
                        font-mono
                        text-[8px]
                        uppercase
                        tracking-[0.16em]
                        text-zinc-400

                        dark:text-zinc-600
                    ">
                    {{techStack.reduce(
                        (total, stack) => total + stack.items.length,
                        0
                    )}}
                    TOOLS / TECHNOLOGIES
                </div>
            </div>
        </div>
    </section>
</template>

// src/components/sections/techstack/Techstack.tsx
"use client";

import {
    Braces,
    Code2,
    Database,
    Globe,
    Headphones,
    Laptop,
    Network,
    Server,
    Settings,
    Wrench,
} from "lucide-react";

import adobePhotoshop from "@/assets/icons/adobephotoshop.svg";
import anydesk from "@/assets/icons/anydesk.svg";
import bootstrap from "@/assets/icons/bootstrap.svg";
import canva from "@/assets/icons/canva.svg";
import capcut from "@/assets/icons/capcut.svg";
import chartdotjs from "@/assets/icons/chartdotjs.svg";
import chatgpt from "@/assets/icons/chatgpt.svg";
import css from "@/assets/icons/css.svg";
import figma from "@/assets/icons/figma.svg";
import git from "@/assets/icons/git.svg";
import github from "@/assets/icons/github.svg";
import html5 from "@/assets/icons/html5.svg";
import javascript from "@/assets/icons/javascript.svg";
import mysql from "@/assets/icons/mysql.svg";
import nextdotjs from "@/assets/icons/nextdotjs.svg";
import php from "@/assets/icons/php.svg";
import reactquery from "@/assets/icons/reactquery.svg";
import tailwindcss from "@/assets/icons/tailwindcss.svg";
import teamviewer from "@/assets/icons/teamviewer.svg";
import typescript from "@/assets/icons/typescript.svg";
import vite from "@/assets/icons/vite.svg";
import vscode from "@/assets/icons/vscode.svg";
import vuedotjs from "@/assets/icons/vuedotjs.svg";
import xampp from "@/assets/icons/xampp.svg";

type TechItem = {
    name: string;
    icon?: string;
    brandColor?: string;
};

type TechCategory = {
    title: string;
    description: string;
    icon: typeof Code2;
    technologies: TechItem[];
};

const techCategories: TechCategory[] = [
    {
        title: "IT Support",
        description:
            "Technical support, troubleshooting, remote assistance, and system maintenance.",
        icon: Headphones,
        technologies: [
            {
                name: "Windows",
                brandColor: "#0078D4",
            },
            {
                name: "Hardware Troubleshooting",
                brandColor: "#22D3EE",
            },
            {
                name: "Software Troubleshooting",
                brandColor: "#8B5CF6",
            },
            {
                name: "Printer Support",
                brandColor: "#64748B",
            },
            {
                name: "AnyDesk",
                icon: anydesk.src,
                brandColor: "#EF443B",
            },
            {
                name: "TeamViewer",
                icon: teamviewer.src,
                brandColor: "#0E8EE9",
            },
            {
                name: "Technical Documentation",
                brandColor: "#14B8A6",
            },
        ],
    },

    {
        title: "Networking",
        description:
            "Networking technologies used for connectivity, diagnostics, and device configuration.",
        icon: Network,
        technologies: [
            {
                name: "LAN",
                brandColor: "#06B6D4",
            },
            {
                name: "TCP/IP",
                brandColor: "#3B82F6",
            },
            {
                name: "Wi-Fi",
                brandColor: "#0EA5E9",
            },
            {
                name: "Network Devices",
                brandColor: "#6366F1",
            },
            {
                name: "Router Configuration",
                brandColor: "#8B5CF6",
            },
        ],
    },

    {
        title: "Frontend Development",
        description:
            "Modern frontend technologies used to build responsive and interactive web interfaces.",
        icon: Globe,
        technologies: [
            {
                name: "HTML5",
                icon: html5.src,
                brandColor: "#E34F26",
            },
            {
                name: "CSS",
                icon: css.src,
                brandColor: "#1572B6",
            },
            {
                name: "JavaScript",
                icon: javascript.src,
                brandColor: "#F7DF1E",
            },
            {
                name: "Vue",
                icon: vuedotjs.src,
                brandColor: "#4FC08D",
            },
            {
                name: "React",
                icon: reactquery.src,
                brandColor: "#61DAFB",
            },
            {
                name: "Next.js",
                icon: nextdotjs.src,
                brandColor: "#000000",
            },
            {
                name: "Tailwind CSS",
                icon: tailwindcss.src,
                brandColor: "#06B6D4",
            },
            {
                name: "Bootstrap",
                icon: bootstrap.src,
                brandColor: "#7952B3",
            },
            {
                name: "TypeScript",
                icon: typescript.src,
                brandColor: "#3178C6",
            },
            {
                name: "Chart.js",
                icon: chartdotjs.src,
                brandColor: "#FF6384",
            },
        ],
    },

    {
        title: "Backend & Database",
        description:
            "Backend technologies and database tools used for business systems and web applications.",
        icon: Database,
        technologies: [
            {
                name: "PHP",
                icon: php.src,
                brandColor: "#777BB4",
            },
            {
                name: "MySQL",
                icon: mysql.src,
                brandColor: "#4479A1",
            },
            {
                name: "SQL",
                brandColor: "#336791",
            },
            {
                name: "Database Design",
                brandColor: "#10B981",
            },
            {
                name: "phpMyAdmin",
                brandColor: "#6C78AF",
            },
        ],
    },

    {
        title: "Development Tools",
        description:
            "Tools used for coding, version control, local development, and project workflows.",
        icon: Wrench,
        technologies: [
            {
                name: "VS Code",
                icon: vscode.src,
                brandColor: "#007ACC",
            },
            {
                name: "Git",
                icon: git.src,
                brandColor: "#F05032",
            },
            {
                name: "GitHub",
                icon: github.src,
                brandColor: "#181717",
            },
            {
                name: "XAMPP",
                icon: xampp.src,
                brandColor: "#FB7A24",
            },
            {
                name: "Vite",
                icon: vite.src,
                brandColor: "#646CFF",
            },
            {
                name: "Composer",
                brandColor: "#885630",
            },
        ],
    },

    {
        title: "Creative & Productivity",
        description:
            "Creative, design, AI, and productivity tools used alongside development and technical work.",
        icon: Laptop,
        technologies: [
            {
                name: "Adobe Photoshop",
                icon: adobePhotoshop.src,
                brandColor: "#31A8FF",
            },
            {
                name: "CapCut",
                icon: capcut.src,
                brandColor: "#000000",
            },
            {
                name: "ChatGPT",
                icon: chatgpt.src,
                brandColor: "#000000",
            },
            {
                name: "Canva",
                icon: canva.src,
                brandColor: "#00C4CC",
            },
            {
                name: "Figma",
                icon: figma.src,
                brandColor: "#F24E1E",
            },
        ],
    },
];

const coreFocus = [
    {
        label: "IT Support",
        icon: Headphones,
    },
    {
        label: "Web Development",
        icon: Braces,
    },
    {
        label: "Networking",
        icon: Network,
    },
    {
        label: "Systems",
        icon: Server,
    },
];

function TechnologyIcon({ technology }: { technology: TechItem }) {
    const isThemeAwareIcon =
        technology.name === "Next.js" ||
        technology.name === "ChatGPT";

    /*
     * Technologies with an actual SVG logo.
     *
     * The SVG is used as a CSS mask so we can apply the exact
     * brand color on hover without changing the shape of the logo.
     */
    if (technology.icon && !isThemeAwareIcon) {
        return (
            <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-zinc-100 dark:bg-zinc-800">
                <span
                    aria-hidden="true"
                    className="h-4 w-4 bg-zinc-400 opacity-60 transition-all duration-300 group-hover/tech:bg-[var(--brand-color)] group-hover/tech:opacity-100 dark:bg-zinc-500 dark:group-hover/tech:bg-[var(--brand-color)]"
                    style={
                        {
                            "--brand-color":
                                technology.brandColor ?? "#06B6D4",
                            "--icon-url": `url(${technology.icon})`,
                            maskImage: "var(--icon-url)",
                            WebkitMaskImage: "var(--icon-url)",
                            maskRepeat: "no-repeat",
                            WebkitMaskRepeat: "no-repeat",
                            maskPosition: "center",
                            WebkitMaskPosition: "center",
                            maskSize: "contain",
                            WebkitMaskSize: "contain",
                        } as React.CSSProperties
                    }
                />
            </div>
        );
    }

    /*
     * Next.js and ChatGPT:
     *
     * Light mode = black
     * Dark mode = white
     *
     * These two intentionally remain monochrome.
     */
    if (technology.icon && isThemeAwareIcon) {
        return (
            <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-zinc-100 dark:bg-zinc-800">
                <span
                    aria-hidden="true"
                    className="h-4 w-4 bg-black dark:bg-white"
                    style={{
                        maskImage: `url(${technology.icon})`,
                        WebkitMaskImage: `url(${technology.icon})`,
                        maskRepeat: "no-repeat",
                        WebkitMaskRepeat: "no-repeat",
                        maskPosition: "center",
                        WebkitMaskPosition: "center",
                        maskSize: "contain",
                        WebkitMaskSize: "contain",
                    }}
                />
            </div>
        );
    }

    /*
     * Technologies without an actual logo.
     *
     * These use a generic Code2 icon and change to their
     * assigned color when the technology item is hovered.
     */
    return (
        <div
            className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-zinc-100 text-zinc-400 transition-colors duration-300 group-hover/tech:text-[var(--brand-color)] dark:bg-zinc-800 dark:text-zinc-500 dark:group-hover/tech:text-[var(--brand-color)]"
            style={
                {
                    "--brand-color":
                        technology.brandColor ?? "#06B6D4",
                } as React.CSSProperties
            }
        >
            <Code2 size={14} />
        </div>
    );
}

export default function TechStack() {
    const totalTechnologies = techCategories.reduce(
        (total, category) => total + category.technologies.length,
        0
    );

    return (
        <section id="techstack" className="scroll-mt-20 space-y-6">
            {/* Section Header */}
            <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                <div>
                    <div className="mb-2 flex items-center gap-2">
                        <span className="h-px w-6 bg-cyan-500" />

                        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-500">
                            Tech Stack
                        </p>
                    </div>

                    <h2 className="text-2xl font-bold tracking-tight text-zinc-950 dark:text-white sm:text-3xl">
                        Technologies & Tools
                    </h2>

                    <p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500 dark:text-zinc-400">
                        The technologies, tools, and technical areas I use
                        across IT support, networking, web development,
                        databases, and creative workflows.
                    </p>
                </div>

                {/* Technology Count */}
                <div className="flex w-fit items-center gap-2 rounded-xl border border-zinc-200 bg-white px-3 py-2 dark:border-zinc-800 dark:bg-zinc-900/60">
                    <Code2 size={15} className="text-cyan-500" />

                    <span className="text-xs font-medium text-zinc-500 dark:text-zinc-400">
                        {totalTechnologies} Technologies
                    </span>
                </div>
            </div>

            {/* Technology Categories */}
            <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                {techCategories.map((category) => {
                    const Icon = category.icon;

                    return (
                        <article
                            key={category.title}
                            className="group relative overflow-hidden rounded-2xl border border-zinc-200 bg-white p-5 transition-all duration-300 hover:-translate-y-1 hover:border-cyan-500/30 hover:shadow-xl hover:shadow-cyan-500/5 dark:border-zinc-800 dark:bg-zinc-900/60 dark:hover:border-cyan-500/30"
                        >
                            {/* Hover Glow */}
                            <div className="pointer-events-none absolute right-0 top-0 h-32 w-32 translate-x-10 -translate-y-10 rounded-full bg-cyan-500/10 opacity-0 blur-3xl transition-all duration-500 group-hover:translate-x-0 group-hover:translate-y-0 group-hover:opacity-100" />

                            {/* Left Accent */}
                            <div className="absolute bottom-0 left-0 top-0 w-0.5 origin-bottom scale-y-0 bg-cyan-500 transition-transform duration-500 group-hover:scale-y-100" />

                            {/* Category Header */}
                            <div className="relative z-10 flex items-start gap-3">
                                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-cyan-500/20 bg-cyan-500/10 transition-all duration-300 group-hover:border-cyan-500/40 group-hover:bg-cyan-500/15">
                                    <Icon
                                        size={18}
                                        className="text-cyan-500"
                                    />
                                </div>

                                <div className="min-w-0">
                                    <h3 className="text-sm font-semibold text-zinc-950 dark:text-white">
                                        {category.title}
                                    </h3>

                                    <p className="mt-1 text-[11px] leading-5 text-zinc-500 dark:text-zinc-400">
                                        {category.description}
                                    </p>
                                </div>
                            </div>

                            {/* Technologies */}
                            <div className="relative z-10 mt-5 grid grid-cols-2 gap-2">
                                {category.technologies.map((technology) => (
                                    <div
                                        key={technology.name}
                                        className="group/tech flex min-w-0 items-center gap-2 rounded-xl border border-zinc-200 bg-zinc-50 px-2.5 py-2 transition-all duration-300 hover:border-cyan-500/30 hover:bg-white dark:border-zinc-800 dark:bg-zinc-950/60 dark:hover:bg-zinc-900"
                                        style={
                                            {
                                                "--brand-color":
                                                    technology.brandColor ??
                                                    "#06B6D4",
                                            } as React.CSSProperties
                                        }
                                    >
                                        <TechnologyIcon
                                            technology={technology}
                                        />

                                        {/* Technology Name */}
                                        <span className="min-w-0 truncate text-[10px] font-medium text-zinc-600 dark:text-zinc-400">
                                            {technology.name}
                                        </span>
                                    </div>
                                ))}
                            </div>
                        </article>
                    );
                })}
            </div>

            {/* Core Focus */}
            <div className="relative overflow-hidden rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900/60 sm:p-6">
                <div className="pointer-events-none absolute right-0 top-0 h-40 w-40 translate-x-16 -translate-y-16 rounded-full bg-cyan-500/10 blur-3xl" />

                <div className="relative z-10 flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
                    <div>
                        <div className="flex items-center gap-2">
                            <Settings
                                size={16}
                                className="text-cyan-500"
                            />

                            <h3 className="text-sm font-semibold text-zinc-950 dark:text-white">
                                Core Focus
                            </h3>
                        </div>

                        <p className="mt-2 max-w-2xl text-xs leading-5 text-zinc-500 dark:text-zinc-400">
                            Combining practical IT support, troubleshooting,
                            networking, and web development to build and
                            maintain reliable technical solutions.
                        </p>
                    </div>

                    <div className="flex flex-wrap gap-2">
                        {coreFocus.map((focus) => {
                            const FocusIcon = focus.icon;

                            return (
                                <div
                                    key={focus.label}
                                    className="inline-flex items-center gap-2 rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-[10px] font-semibold text-zinc-500 transition-all duration-300 hover:border-cyan-500/20 hover:bg-cyan-500/5 hover:text-cyan-500 dark:border-zinc-800 dark:bg-zinc-950/60 dark:text-zinc-400 dark:hover:text-cyan-400"
                                >
                                    <FocusIcon size={13} />

                                    {focus.label}
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>
        </section>
    );
}
